name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p site/files
          echo "Hello, world!" > site/files/index.html

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: site
          path: site/
